version: '2'
services:
  web:
    build: .
    env_file:
     - ./wechat.env
    volumes:
     - ./db:/usr/src/app/db
    networks:
     - globalproxy_default
     - default
    restart: always
volumes:
  db:
    driver: local
networks:
  globalproxy_default:
    external: true
