version: '2'
services:
  web:
    build: .
    env_file:
     - ./wechat.env
    volumes:
     - db:/usr/src/app/db
volumes:
  db:
    driver: local
networks:
  globalproxy_default:
    external: true
